- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: rg-RishiK
      location: centralindia
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: rg-RishiK
      name: Vnet-RishiK
      address_prefixes: "192.168.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: rg-RishiK
      name: Subnet-1
      address_prefix: "192.168.10.0/24"
      virtual_network: Vnet-RishiK
  - name: Create App Service Plan
    azure_rm_appserviceplan:
      resource_group: rg-RishiK
      name: WebApp-Plan
      location: centralindia
      is_linux: true
      sku: S1
      number_of_workers: 1
  - name: Create a windows web app with node, php
    azure_rm_webapp:
      resource_group: rg-RishiK
      name: WebApp-RishiK
      plan:
        resource_group: rg-RishiK
        name: WebApp-Plan
      app_settings:
        testkey: testvalue
      frameworks:
        - name: "node"
          version: 6.6
        - name: "php"
          version: "7.0"